/**
* Kyouen API
* Kyouen server's API.
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hm.orz.chaos114.android.tumekyouen.network.models


import com.squareup.moshi.Json
/**
 * 
 * @param stage 0: no stone<br>1: black stone<br>2: white stone (selected)
 */

data class ClearStage (
    /* 0: no stone<br>1: black stone<br>2: white stone (selected) */
    @Json(name = "stage")
    val stage: kotlin.String
)

