/**
* Kyouen API
* Kyouen server's API.
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hm.orz.chaos114.android.tumekyouen.network.models


import com.squareup.moshi.Json
/**
 * 
 * @param stageNo 
 * @param size 
 * @param stage 
 * @param creator 
 * @param registDate date in UTC
 */

data class Stage (
    @Json(name = "stage_no")
    val stageNo: kotlin.Long,
    @Json(name = "size")
    val size: kotlin.Long,
    @Json(name = "stage")
    val stage: kotlin.String,
    @Json(name = "creator")
    val creator: kotlin.String,
    /* date in UTC */
    @Json(name = "regist_date")
    val registDate: kotlin.String
)

