/**
* Kyouen API
* Kyouen server's API.
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hm.orz.chaos114.android.tumekyouen.network.models


import com.squareup.moshi.Json
/**
 * 
 * @param count 
 * @param lastUpdatedAt date in UTC
 */

data class Statics (
    @Json(name = "count")
    val count: kotlin.Long,
    /* date in UTC */
    @Json(name = "last_updated_at")
    val lastUpdatedAt: kotlin.String
)

