language: android
env:
  global:
    - DEPLOYGATE_USER=noboru-i
    - secure: "deWo5doc+JgIQYh7KoqF+E1eOUVcoH0Iob/gYGoTGbt5xvEdrjfqtV0c/flwEla3Z38aHAyOMq52m4ZQheaEIy7TpenAZ3Dwi0tQmuV1BSQ+u1uoQBlWOAjNojPHPJUoEL4vItBMkJz6k5ts6UXUz2r0ekaUp1lmZXyBsBuGUGA="
android:
  update_sdk: true
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-19
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - '.*intel.+'
script:
  - ./gradlew uploadDeployGateDebug
